"""Batch tests for the enrichment join, scenario synthesis, and the shared consumer
pipeline. Uses the real CSVs in data/static, so it also validates the fleet data
and join keys. No Kafka/cluster needed."""
import csv

import pytest
from pyspark.sql import SparkSession, Window
from pyspark.sql import functions as F

from shared.schemas import EVENT_SCHEMA, ALERT_OUTPUT_COLUMNS
from shared.enrichment import load_fleet, enrich
from shared.scenarios import build_events, SCENARIOS
from shared.pipeline import alerts_stream

STATIC = "data/static"


def _rows(name):
    with open(f"{STATIC}/{name}", newline="") as f:
        return list(csv.DictReader(f))


def _thresholds():
    return {r["freezer_type"]: (float(r["temperature_upper_limit"]), int(r["door_open_limit_seconds"]))
            for r in _rows("device_thresholds.csv")}


FLEET_SIZE = len(_rows("freezer_metadata.csv"))    # generated by scripts/gen_fleet.py


@pytest.fixture(scope="session")
def spark():
    s = (SparkSession.builder.master("local[1]").appName("pipeline-tests")
         .config("spark.sql.shuffle.partitions", "1").config("spark.ui.enabled", "false")
         .getOrCreate())
    yield s
    s.stop()


def test_fleet_loads_with_thresholds(spark):
    fleet = load_fleet(spark, STATIC)
    assert fleet.count() == FLEET_SIZE
    # every freezer resolved its thresholds and site (join keys all match)
    assert fleet.filter(F.col("temperature_upper_limit").isNull()).count() == 0
    assert fleet.filter(F.col("door_open_limit_seconds").isNull()).count() == 0
    assert fleet.filter(F.col("site_name").isNull()).count() == 0
    # a sampled freezer's threshold matches its type's row in device_thresholds
    row = fleet.orderBy("freezer_id").first()
    lim, dsec = _thresholds()[row["freezer_type"]]
    assert row["temperature_upper_limit"] == lim
    assert row["door_open_limit_seconds"] == dsec


@pytest.mark.parametrize("scenario", SCENARIOS)
def test_build_events_matches_event_schema(spark, scenario):
    fleet = load_fleet(spark, STATIC).withColumn(
        "idx", F.row_number().over(Window.orderBy("freezer_id")) - 1)
    events = build_events(fleet, scenario)
    assert set(events.columns) == {f.name for f in EVENT_SCHEMA.fields}
    assert events.count() == FLEET_SIZE
    assert events.select("scenario_name").distinct().collect()[0][0] == scenario


def test_hot_zone_events_flow_through_pipeline(spark):
    fleet = load_fleet(spark, STATIC).withColumn(
        "idx", F.row_number().over(Window.orderBy("freezer_id")) - 1)
    # fleet_hot_zone pushes many units over their limit -> alerts should appear.
    events = build_events(fleet, "fleet_hot_zone")
    out = alerts_stream(events, fleet, "rtm")
    assert list(out.columns) == ALERT_OUTPUT_COLUMNS
    assert out.count() > 0
    modes = {r["source_mode"] for r in out.select("source_mode").distinct().collect()}
    assert modes == {"rtm"}
